spring.application.name=HR-Management-portal

server.port=8079
spring.datasource.url=jdbc:mysql://localhost:3306/hmp_internship
spring.datasource.username=root
spring.datasource.password=Tejas@258
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true